// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package argus_db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type StampAnomaly struct {
	ID        pgtype.UUID
	SerialID  string
	Target    string
	Port      int32
	Metric    string
	Ts        pgtype.Timestamptz
	Value     float64
	Mean      float64
	Stddev    float64
	ZScore    float64
	CreatedAt pgtype.Timestamptz
}

type StampBaseline struct {
	SerialID  string
	Target    string
	Port      int32
	Metric    string
	Mean      float64
	Variance  float64
	N         int64
	LastSeen  pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type StampMeasurement struct {
	ID            pgtype.UUID
	Timestamp     pgtype.Timestamptz
	SerialID      string
	AgentConfigID pgtype.UUID
	Target        string
	Port          int32
	Sent          int32
	Received      int32
	Loss          float64
}

type StampProbe struct {
	MeasurementID pgtype.UUID
	Tx            pgtype.Timestamptz
	IsLost        bool
	Rx            pgtype.Timestamptz
	Rtt           pgtype.Int8
	ForwardDelay  pgtype.Int8
	BackwardDelay pgtype.Int8
}
