// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package argus_db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const fetchNewLossSamples = `-- name: FetchNewLossSamples :many
SELECT timestamp, loss
FROM stamp_measurements
WHERE serial_id = $1 AND target = $2 AND port = $3
  AND timestamp > $4 AND timestamp <= $5
ORDER BY timestamp ASC
`

type FetchNewLossSamplesParams struct {
	SerialID    string
	Target      string
	Port        int32
	Timestamp   pgtype.Timestamptz
	Timestamp_2 pgtype.Timestamptz
}

type FetchNewLossSamplesRow struct {
	Timestamp pgtype.Timestamptz
	Loss      float64
}

func (q *Queries) FetchNewLossSamples(ctx context.Context, arg FetchNewLossSamplesParams) ([]FetchNewLossSamplesRow, error) {
	rows, err := q.db.Query(ctx, fetchNewLossSamples,
		arg.SerialID,
		arg.Target,
		arg.Port,
		arg.Timestamp,
		arg.Timestamp_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchNewLossSamplesRow
	for rows.Next() {
		var i FetchNewLossSamplesRow
		if err := rows.Scan(&i.Timestamp, &i.Loss); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBaseline = `-- name: GetBaseline :one
SELECT mean, variance, n, last_seen
FROM stamp_baselines
WHERE serial_id = $1 AND target = $2 AND port = $3 AND metric = $4
`

type GetBaselineParams struct {
	SerialID string
	Target   string
	Port     int32
	Metric   string
}

type GetBaselineRow struct {
	Mean     float64
	Variance float64
	N        int64
	LastSeen pgtype.Timestamptz
}

func (q *Queries) GetBaseline(ctx context.Context, arg GetBaselineParams) (GetBaselineRow, error) {
	row := q.db.QueryRow(ctx, getBaseline,
		arg.SerialID,
		arg.Target,
		arg.Port,
		arg.Metric,
	)
	var i GetBaselineRow
	err := row.Scan(
		&i.Mean,
		&i.Variance,
		&i.N,
		&i.LastSeen,
	)
	return i, err
}

const insertAnomaly = `-- name: InsertAnomaly :exec
INSERT INTO stamp_anomalies
(serial_id, target, port, metric, ts, value, mean, stddev, z_score)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertAnomalyParams struct {
	SerialID string
	Target   string
	Port     int32
	Metric   string
	Ts       pgtype.Timestamptz
	Value    float64
	Mean     float64
	Stddev   float64
	ZScore   float64
}

func (q *Queries) InsertAnomaly(ctx context.Context, arg InsertAnomalyParams) error {
	_, err := q.db.Exec(ctx, insertAnomaly,
		arg.SerialID,
		arg.Target,
		arg.Port,
		arg.Metric,
		arg.Ts,
		arg.Value,
		arg.Mean,
		arg.Stddev,
		arg.ZScore,
	)
	return err
}

const listActiveSeries = `-- name: ListActiveSeries :many
SELECT DISTINCT serial_id, target, port
FROM stamp_measurements
WHERE timestamp >= $1
`

type ListActiveSeriesRow struct {
	SerialID string
	Target   string
	Port     int32
}

func (q *Queries) ListActiveSeries(ctx context.Context, timestamp pgtype.Timestamptz) ([]ListActiveSeriesRow, error) {
	rows, err := q.db.Query(ctx, listActiveSeries, timestamp)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveSeriesRow
	for rows.Next() {
		var i ListActiveSeriesRow
		if err := rows.Scan(&i.SerialID, &i.Target, &i.Port); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBaseline = `-- name: UpsertBaseline :exec
INSERT INTO stamp_baselines
(serial_id, target, port, metric, mean, variance, n, last_seen, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, now())
ON CONFLICT (serial_id, target, port, metric) DO UPDATE SET
                                                            mean       = EXCLUDED.mean,
                                                            variance   = EXCLUDED.variance,
                                                            n          = EXCLUDED.n,
                                                            last_seen  = EXCLUDED.last_seen,
                                                            updated_at = now()
`

type UpsertBaselineParams struct {
	SerialID string
	Target   string
	Port     int32
	Metric   string
	Mean     float64
	Variance float64
	N        int64
	LastSeen pgtype.Timestamptz
}

func (q *Queries) UpsertBaseline(ctx context.Context, arg UpsertBaselineParams) error {
	_, err := q.db.Exec(ctx, upsertBaseline,
		arg.SerialID,
		arg.Target,
		arg.Port,
		arg.Metric,
		arg.Mean,
		arg.Variance,
		arg.N,
		arg.LastSeen,
	)
	return err
}
