stages:
  - lint
  - test

editorconfig:
  stage: lint
  script:
    - make lint.editorconfig
  tags:
    - docker
    - go

integration:
  stage: test
  script:
    - make test.build
    - make test.integration
  after_script:
    - docker compose -f docker-compose.test.yaml down
  rules:
    - changes:
        - libs/stamp/**/*
        - libs/scamper-client/**/*
        - docker-compose.test.yaml
        - docker/tests/**/*
        - docker/scamper.build.Dockerfile
    - when: manual
      allow_failure: true
  tags:
    - docker
    - go

unit:
  stage: test
  script:
    - make test.unit
  tags:
    - docker
    - go

lint:
  image: golangci/golangci-lint:latest
  stage: lint
  cache:
    key: golangci-lint-$CI_COMMIT_REF_SLUG
    paths:
      - .cache/golangci-lint
      - .cache/go/pkg/mod
  variables:
    GOLANGCI_LINT_CACHE: $CI_PROJECT_DIR/.cache/golangci-lint
    GOPATH: $CI_PROJECT_DIR/.cache/go
  script:
    - make lint
