services:
  stamp-suite-reflector:
    image: test-stamp-suite:latest
    container_name: cepheus-test-reflector-stamp-suite
    ports:
      - "862:862/udp"
    command: "./target/release/stamp-suite -i"

  scamper-test-suite:
    image: test-scamper-suite:latest
    container_name: cepheus-test-scamper-scamper-suite
    network_mode: host
    privileged: true
    volumes:
      - type: bind
        source: ./dist/agent/
        target: /opt/agent/
      - type: bind
        source: .
        target: /app