// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package stampprocessor_db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type StampMeasurement struct {
	ID            pgtype.UUID
	Timestamp     pgtype.Timestamptz
	SerialID      string
	AgentConfigID pgtype.UUID
	Target        string
	Port          int32
	Sent          int32
	Received      int32
	Loss          float64
}

type StampProbe struct {
	MeasurementID pgtype.UUID
	Tx            pgtype.Timestamptz
	IsLost        bool
	Rx            pgtype.Timestamptz
	Rtt           pgtype.Int8
	ForwardDelay  pgtype.Int8
	BackwardDelay pgtype.Int8
}
