// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package argus_db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachFindingToEvent = `-- name: AttachFindingToEvent :exec
UPDATE argus_findings
SET event_id = $1
WHERE id = $2
`

type AttachFindingToEventParams struct {
	EventID pgtype.UUID
	ID      pgtype.UUID
}

func (q *Queries) AttachFindingToEvent(ctx context.Context, arg AttachFindingToEventParams) error {
	_, err := q.db.Exec(ctx, attachFindingToEvent, arg.EventID, arg.ID)
	return err
}

const closeEvent = `-- name: CloseEvent :exec
UPDATE argus_events
SET status    = 'closed',
    closed_at = $2
WHERE id = $1
`

type CloseEventParams struct {
	ID       pgtype.UUID
	ClosedAt pgtype.Timestamptz
}

func (q *Queries) CloseEvent(ctx context.Context, arg CloseEventParams) error {
	_, err := q.db.Exec(ctx, closeEvent, arg.ID, arg.ClosedAt)
	return err
}

const fetchPingSamples = `-- name: FetchPingSamples :many
SELECT timestamp, rtt_p95_ns, sent, received
FROM ping_measurements
WHERE serial_id = $1
  AND target = $2
  AND timestamp > $3
  AND timestamp <= $4
`

type FetchPingSamplesParams struct {
	SerialID string
	Target   string
	After    pgtype.Timestamptz
	Before   pgtype.Timestamptz
}

type FetchPingSamplesRow struct {
	Timestamp pgtype.Timestamptz
	RttP95Ns  int64
	Sent      int32
	Received  int32
}

func (q *Queries) FetchPingSamples(ctx context.Context, arg FetchPingSamplesParams) ([]FetchPingSamplesRow, error) {
	rows, err := q.db.Query(ctx, fetchPingSamples,
		arg.SerialID,
		arg.Target,
		arg.After,
		arg.Before,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchPingSamplesRow
	for rows.Next() {
		var i FetchPingSamplesRow
		if err := rows.Scan(
			&i.Timestamp,
			&i.RttP95Ns,
			&i.Sent,
			&i.Received,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fetchStampSamples = `-- name: FetchStampSamples :many
SELECT timestamp, rtt_p95_ns, fwd_p95_ns, bwd_p95_ns, sent, received
FROM stamp_measurements
WHERE serial_id = $1
  AND target = $2
  AND port = $3
  AND timestamp > $4
  AND timestamp <= $5
`

type FetchStampSamplesParams struct {
	SerialID string
	Target   string
	Port     int32
	After    pgtype.Timestamptz
	Before   pgtype.Timestamptz
}

type FetchStampSamplesRow struct {
	Timestamp pgtype.Timestamptz
	RttP95Ns  int64
	FwdP95Ns  int64
	BwdP95Ns  int64
	Sent      int32
	Received  int32
}

func (q *Queries) FetchStampSamples(ctx context.Context, arg FetchStampSamplesParams) ([]FetchStampSamplesRow, error) {
	rows, err := q.db.Query(ctx, fetchStampSamples,
		arg.SerialID,
		arg.Target,
		arg.Port,
		arg.After,
		arg.Before,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchStampSamplesRow
	for rows.Next() {
		var i FetchStampSamplesRow
		if err := rows.Scan(
			&i.Timestamp,
			&i.RttP95Ns,
			&i.FwdP95Ns,
			&i.BwdP95Ns,
			&i.Sent,
			&i.Received,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fetchTraceSamples = `-- name: FetchTraceSamples :many
SELECT timestamp, asn_path_hash, link_path_hash
FROM trace_measurements
WHERE serial_id = $1
  AND src = $2
  AND dst = $3
  AND type = $4
`

type FetchTraceSamplesParams struct {
	SerialID string
	Src      netip.Addr
	Dst      netip.Addr
	Type     string
}

type FetchTraceSamplesRow struct {
	Timestamp    pgtype.Timestamptz
	AsnPathHash  string
	LinkPathHash string
}

func (q *Queries) FetchTraceSamples(ctx context.Context, arg FetchTraceSamplesParams) ([]FetchTraceSamplesRow, error) {
	rows, err := q.db.Query(ctx, fetchTraceSamples,
		arg.SerialID,
		arg.Src,
		arg.Dst,
		arg.Type,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchTraceSamplesRow
	for rows.Next() {
		var i FetchTraceSamplesRow
		if err := rows.Scan(&i.Timestamp, &i.AsnPathHash, &i.LinkPathHash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBaseline = `-- name: GetBaseline :one
SELECT state, n, last_seen
FROM argus_baselines
WHERE serial_id = $1
  AND target = $2
  AND port = $3
  AND metric = $4
  AND detector = $5
  AND src_ip = $6
`

type GetBaselineParams struct {
	SerialID string
	Target   string
	Port     int32
	Metric   string
	Detector string
	SrcIp    string
}

type GetBaselineRow struct {
	State    []byte
	N        int64
	LastSeen pgtype.Timestamptz
}

func (q *Queries) GetBaseline(ctx context.Context, arg GetBaselineParams) (GetBaselineRow, error) {
	row := q.db.QueryRow(ctx, getBaseline,
		arg.SerialID,
		arg.Target,
		arg.Port,
		arg.Metric,
		arg.Detector,
		arg.SrcIp,
	)
	var i GetBaselineRow
	err := row.Scan(&i.State, &i.N, &i.LastSeen)
	return i, err
}

const getPolicyState = `-- name: GetPolicyState :one
SELECT serial_id,
       target,
       port,
       metric,
       detector,
       status,
       score,
       score_updated_at,
       open_event_id,
       pending_findings,
       entered_status_at
FROM argus_policy_state
WHERE serial_id = $1
  AND target = $2
  AND port = $3
  AND metric = $4
  AND detector = $5
  AND src_ip = $6
`

type GetPolicyStateParams struct {
	SerialID string
	Target   string
	Port     int32
	Metric   string
	Detector string
	SrcIp    string
}

type GetPolicyStateRow struct {
	SerialID        string
	Target          string
	Port            int32
	Metric          string
	Detector        string
	Status          string
	Score           float64
	ScoreUpdatedAt  pgtype.Timestamptz
	OpenEventID     pgtype.UUID
	PendingFindings []pgtype.UUID
	EnteredStatusAt pgtype.Timestamptz
}

func (q *Queries) GetPolicyState(ctx context.Context, arg GetPolicyStateParams) (GetPolicyStateRow, error) {
	row := q.db.QueryRow(ctx, getPolicyState,
		arg.SerialID,
		arg.Target,
		arg.Port,
		arg.Metric,
		arg.Detector,
		arg.SrcIp,
	)
	var i GetPolicyStateRow
	err := row.Scan(
		&i.SerialID,
		&i.Target,
		&i.Port,
		&i.Metric,
		&i.Detector,
		&i.Status,
		&i.Score,
		&i.ScoreUpdatedAt,
		&i.OpenEventID,
		&i.PendingFindings,
		&i.EnteredStatusAt,
	)
	return i, err
}

const insertFinding = `-- name: InsertFinding :one
INSERT INTO argus_findings
(serial_id, target, port, metric, detector, ts, value, severity, details)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (serial_id, target, port, metric, detector, ts) DO NOTHING
RETURNING id
`

type InsertFindingParams struct {
	SerialID string
	Target   string
	Port     int32
	Metric   string
	Detector string
	Ts       pgtype.Timestamptz
	Value    float64
	Severity float64
	Details  []byte
}

func (q *Queries) InsertFinding(ctx context.Context, arg InsertFindingParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertFinding,
		arg.SerialID,
		arg.Target,
		arg.Port,
		arg.Metric,
		arg.Detector,
		arg.Ts,
		arg.Value,
		arg.Severity,
		arg.Details,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listActivePingSeries = `-- name: ListActivePingSeries :many
SELECT DISTINCT serial_id, target
FROM ping_measurements
WHERE timestamp >= $1
`

type ListActivePingSeriesRow struct {
	SerialID string
	Target   string
}

func (q *Queries) ListActivePingSeries(ctx context.Context, timestamp pgtype.Timestamptz) ([]ListActivePingSeriesRow, error) {
	rows, err := q.db.Query(ctx, listActivePingSeries, timestamp)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActivePingSeriesRow
	for rows.Next() {
		var i ListActivePingSeriesRow
		if err := rows.Scan(&i.SerialID, &i.Target); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveStampSeries = `-- name: ListActiveStampSeries :many
SELECT DISTINCT serial_id, target, port
FROM stamp_measurements
WHERE timestamp >= $1
`

type ListActiveStampSeriesRow struct {
	SerialID string
	Target   string
	Port     int32
}

func (q *Queries) ListActiveStampSeries(ctx context.Context, timestamp pgtype.Timestamptz) ([]ListActiveStampSeriesRow, error) {
	rows, err := q.db.Query(ctx, listActiveStampSeries, timestamp)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveStampSeriesRow
	for rows.Next() {
		var i ListActiveStampSeriesRow
		if err := rows.Scan(&i.SerialID, &i.Target, &i.Port); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveTraceSeries = `-- name: ListActiveTraceSeries :many
SELECT DISTINCT serial_id, src, dst, method
FROM trace_measurements
WHERE timestamp >= $1
`

type ListActiveTraceSeriesRow struct {
	SerialID string
	Src      netip.Addr
	Dst      netip.Addr
	Method   string
}

func (q *Queries) ListActiveTraceSeries(ctx context.Context, timestamp pgtype.Timestamptz) ([]ListActiveTraceSeriesRow, error) {
	rows, err := q.db.Query(ctx, listActiveTraceSeries, timestamp)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveTraceSeriesRow
	for rows.Next() {
		var i ListActiveTraceSeriesRow
		if err := rows.Scan(
			&i.SerialID,
			&i.Src,
			&i.Dst,
			&i.Method,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNonCleanPolicyStates = `-- name: ListNonCleanPolicyStates :many
SELECT serial_id,
       target,
       port,
       metric,
       detector,
       status,
       score,
       score_updated_at,
       open_event_id,
       pending_findings,
       entered_status_at
FROM argus_policy_state
WHERE status <> 'clean'
`

type ListNonCleanPolicyStatesRow struct {
	SerialID        string
	Target          string
	Port            int32
	Metric          string
	Detector        string
	Status          string
	Score           float64
	ScoreUpdatedAt  pgtype.Timestamptz
	OpenEventID     pgtype.UUID
	PendingFindings []pgtype.UUID
	EnteredStatusAt pgtype.Timestamptz
}

func (q *Queries) ListNonCleanPolicyStates(ctx context.Context) ([]ListNonCleanPolicyStatesRow, error) {
	rows, err := q.db.Query(ctx, listNonCleanPolicyStates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNonCleanPolicyStatesRow
	for rows.Next() {
		var i ListNonCleanPolicyStatesRow
		if err := rows.Scan(
			&i.SerialID,
			&i.Target,
			&i.Port,
			&i.Metric,
			&i.Detector,
			&i.Status,
			&i.Score,
			&i.ScoreUpdatedAt,
			&i.OpenEventID,
			&i.PendingFindings,
			&i.EnteredStatusAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const openEvent = `-- name: OpenEvent :one
INSERT INTO argus_events
(serial_id, target, port, metric, status, opened_at, last_seen_at,
 finding_count, peak_severity, detectors)
VALUES ($1, $2, $3, $4, 'open', $5, $5, $6, $7, $8)
RETURNING id
`

type OpenEventParams struct {
	SerialID     string
	Target       string
	Port         int32
	Metric       string
	OpenedAt     pgtype.Timestamptz
	FindingCount int32
	PeakSeverity float64
	Detectors    []string
}

func (q *Queries) OpenEvent(ctx context.Context, arg OpenEventParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, openEvent,
		arg.SerialID,
		arg.Target,
		arg.Port,
		arg.Metric,
		arg.OpenedAt,
		arg.FindingCount,
		arg.PeakSeverity,
		arg.Detectors,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const updateEventOnFinding = `-- name: UpdateEventOnFinding :exec
UPDATE argus_events
SET last_seen_at  = $2,
    finding_count = finding_count + 1,
    peak_severity = GREATEST(peak_severity, $3),
    detectors     = CASE
                        WHEN $4::TEXT = ANY (detectors) THEN detectors
                        ELSE array_append(detectors, $4::TEXT)
        END
WHERE id = $1
`

type UpdateEventOnFindingParams struct {
	ID           pgtype.UUID
	LastSeenAt   pgtype.Timestamptz
	PeakSeverity float64
	Column4      string
}

func (q *Queries) UpdateEventOnFinding(ctx context.Context, arg UpdateEventOnFindingParams) error {
	_, err := q.db.Exec(ctx, updateEventOnFinding,
		arg.ID,
		arg.LastSeenAt,
		arg.PeakSeverity,
		arg.Column4,
	)
	return err
}

const upsertBaseline = `-- name: UpsertBaseline :exec
INSERT INTO argus_baselines
(serial_id, src_ip, target, port, metric, detector, state, n, last_seen, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, now())
ON CONFLICT (serial_id, src_ip, target, port, metric, detector) DO UPDATE SET state      = EXCLUDED.state,
                                                                              n          = EXCLUDED.n,
                                                                              last_seen  = EXCLUDED.last_seen,
                                                                              updated_at = now()
`

type UpsertBaselineParams struct {
	SerialID string
	SrcIp    string
	Target   string
	Port     int32
	Metric   string
	Detector string
	State    []byte
	N        int64
	LastSeen pgtype.Timestamptz
}

func (q *Queries) UpsertBaseline(ctx context.Context, arg UpsertBaselineParams) error {
	_, err := q.db.Exec(ctx, upsertBaseline,
		arg.SerialID,
		arg.SrcIp,
		arg.Target,
		arg.Port,
		arg.Metric,
		arg.Detector,
		arg.State,
		arg.N,
		arg.LastSeen,
	)
	return err
}

const upsertPolicyState = `-- name: UpsertPolicyState :exec
INSERT INTO argus_policy_state
(serial_id, src_ip, target, port, metric, detector,
 status, score, score_updated_at,
 open_event_id, pending_findings, entered_status_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, now())
ON CONFLICT (serial_id, src_ip, target, port, metric, detector) DO UPDATE SET status            = EXCLUDED.status,
                                                                      score             = EXCLUDED.score,
                                                                      score_updated_at  = EXCLUDED.score_updated_at,
                                                                      open_event_id     = EXCLUDED.open_event_id,
                                                                      pending_findings  = EXCLUDED.pending_findings,
                                                                      entered_status_at = EXCLUDED.entered_status_at,
                                                                      updated_at        = now()
`

type UpsertPolicyStateParams struct {
	SerialID        string
	SrcIp           string
	Target          string
	Port            int32
	Metric          string
	Detector        string
	Status          string
	Score           float64
	ScoreUpdatedAt  pgtype.Timestamptz
	OpenEventID     pgtype.UUID
	PendingFindings []pgtype.UUID
	EnteredStatusAt pgtype.Timestamptz
}

func (q *Queries) UpsertPolicyState(ctx context.Context, arg UpsertPolicyStateParams) error {
	_, err := q.db.Exec(ctx, upsertPolicyState,
		arg.SerialID,
		arg.SrcIp,
		arg.Target,
		arg.Port,
		arg.Metric,
		arg.Detector,
		arg.Status,
		arg.Score,
		arg.ScoreUpdatedAt,
		arg.OpenEventID,
		arg.PendingFindings,
		arg.EnteredStatusAt,
	)
	return err
}
