// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package stampprocessor_db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type StampDatum struct {
	Timestamp     pgtype.Timestamptz
	SerialID      string
	AgentConfigID pgtype.UUID
	Target        string
	Port          int32
	Sent          int32
	Received      int32
	Loss          float64
	AvgRtt        int64
	MinRtt        int64
	MaxRtt        int64
	P50Rtt        int64
	P95Rtt        int64
}
