// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package stampprocessor_db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertStampData = `-- name: InsertStampData :one
INSERT INTO stamp_data
(timestamp, serial_id, target, port, sent, received, loss, avg_rtt, min_rtt, max_rtt, p50_rtt, p95_rtt, agent_config_id)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12, $13)
RETURNING timestamp, serial_id, agent_config_id, target, port, sent, received, loss, avg_rtt, min_rtt, max_rtt, p50_rtt, p95_rtt
`

type InsertStampDataParams struct {
	Timestamp     pgtype.Timestamptz
	SerialID      string
	Target        string
	Port          int32
	Sent          int32
	Received      int32
	Loss          float64
	AvgRtt        int64
	MinRtt        int64
	MaxRtt        int64
	P50Rtt        int64
	P95Rtt        int64
	AgentConfigID pgtype.UUID
}

func (q *Queries) InsertStampData(ctx context.Context, arg InsertStampDataParams) (StampDatum, error) {
	row := q.db.QueryRow(ctx, insertStampData,
		arg.Timestamp,
		arg.SerialID,
		arg.Target,
		arg.Port,
		arg.Sent,
		arg.Received,
		arg.Loss,
		arg.AvgRtt,
		arg.MinRtt,
		arg.MaxRtt,
		arg.P50Rtt,
		arg.P95Rtt,
		arg.AgentConfigID,
	)
	var i StampDatum
	err := row.Scan(
		&i.Timestamp,
		&i.SerialID,
		&i.AgentConfigID,
		&i.Target,
		&i.Port,
		&i.Sent,
		&i.Received,
		&i.Loss,
		&i.AvgRtt,
		&i.MinRtt,
		&i.MaxRtt,
		&i.P50Rtt,
		&i.P95Rtt,
	)
	return i, err
}
