// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package stampprocessor_db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertStampMeasurement = `-- name: InsertStampMeasurement :one
INSERT INTO stamp_measurements (timestamp, serial_id, agent_config_id, target, port, sent, received, loss)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type InsertStampMeasurementParams struct {
	Timestamp     pgtype.Timestamptz
	SerialID      string
	AgentConfigID pgtype.UUID
	Target        string
	Port          int32
	Sent          int32
	Received      int32
	Loss          float64
}

func (q *Queries) InsertStampMeasurement(ctx context.Context, arg InsertStampMeasurementParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertStampMeasurement,
		arg.Timestamp,
		arg.SerialID,
		arg.AgentConfigID,
		arg.Target,
		arg.Port,
		arg.Sent,
		arg.Received,
		arg.Loss,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

type InsertStampProbesParams struct {
	MeasurementID pgtype.UUID
	Tx            pgtype.Timestamptz
	IsLost        bool
	Rx            pgtype.Timestamptz
	Rtt           pgtype.Int8
	ForwardDelay  pgtype.Int8
	BackwardDelay pgtype.Int8
}
