// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package traceprocessor_db

import (
	"context"
)

// iteratorForInsertTraceHop implements pgx.CopyFromSource.
type iteratorForInsertTraceHop struct {
	rows                 []InsertTraceHopParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertTraceHop) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertTraceHop) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Timestamp,
		r.rows[0].MeasurementID,
		r.rows[0].Ip,
		r.rows[0].Ttl,
		r.rows[0].Rtt,
		r.rows[0].IcmpType,
		r.rows[0].IcmpCode,
		r.rows[0].ReplyTtl,
		r.rows[0].Asn,
		r.rows[0].IsNoHop,
	}, nil
}

func (r iteratorForInsertTraceHop) Err() error {
	return nil
}

func (q *Queries) InsertTraceHop(ctx context.Context, arg []InsertTraceHopParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"trace_hops"}, []string{"timestamp", "measurement_id", "ip", "ttl", "rtt", "icmp_type", "icmp_code", "reply_ttl", "asn", "is_no_hop"}, &iteratorForInsertTraceHop{rows: arg})
}
