// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package traceprocessor_db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type TraceHop struct {
	Timestamp     pgtype.Timestamptz
	MeasurementID pgtype.UUID
	Ip            *netip.Addr
	Ttl           int32
	RttMs         pgtype.Float8
	IcmpType      pgtype.Int4
	IcmpCode      pgtype.Int4
	ReplyTtl      pgtype.Int4
	Asn           pgtype.Int4
	IsNoHop       bool
}

type TraceMeasurement struct {
	ID            pgtype.UUID
	SerialID      string
	AgentConfigID pgtype.UUID
	Timestamp     pgtype.Timestamptz
	Type          string
	Src           netip.Addr
	Dst           netip.Addr
	Method        string
	StopReason    string
	HopCount      int32
	PathHash      string
	Raw           []byte
}
