// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package traceprocessor_db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const getExistingIPs = `-- name: GetExistingIPs :many
SELECT ip FROM as_details WHERE ip = ANY($1::inet[])
`

func (q *Queries) GetExistingIPs(ctx context.Context, ips []netip.Addr) ([]netip.Addr, error) {
	rows, err := q.db.Query(ctx, getExistingIPs, ips)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []netip.Addr
	for rows.Next() {
		var ip netip.Addr
		if err := rows.Scan(&ip); err != nil {
			return nil, err
		}
		items = append(items, ip)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHopsByMeasurement = `-- name: GetHopsByMeasurement :many
SELECT timestamp, measurement_id, ip, ttl, rtt, icmp_type, icmp_code, reply_ttl, asn, is_no_hop FROM trace_hops
WHERE measurement_id = $1
ORDER BY ttl ASC
`

func (q *Queries) GetHopsByMeasurement(ctx context.Context, measurementID pgtype.UUID) ([]TraceHop, error) {
	rows, err := q.db.Query(ctx, getHopsByMeasurement, measurementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TraceHop
	for rows.Next() {
		var i TraceHop
		if err := rows.Scan(
			&i.Timestamp,
			&i.MeasurementID,
			&i.Ip,
			&i.Ttl,
			&i.Rtt,
			&i.IcmpType,
			&i.IcmpCode,
			&i.ReplyTtl,
			&i.Asn,
			&i.IsNoHop,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMeasurementsByPath = `-- name: GetMeasurementsByPath :many
SELECT id, serial_id, agent_config_id, timestamp, type, src, dst, method, stop_reason, hop_count, path_hash, raw FROM trace_measurements
WHERE src = $1
  AND dst = $2
  AND timestamp > NOW() - $3::interval
ORDER BY timestamp DESC
`

type GetMeasurementsByPathParams struct {
	Src     netip.Addr
	Dst     netip.Addr
	Column3 pgtype.Interval
}

func (q *Queries) GetMeasurementsByPath(ctx context.Context, arg GetMeasurementsByPathParams) ([]TraceMeasurement, error) {
	rows, err := q.db.Query(ctx, getMeasurementsByPath, arg.Src, arg.Dst, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TraceMeasurement
	for rows.Next() {
		var i TraceMeasurement
		if err := rows.Scan(
			&i.ID,
			&i.SerialID,
			&i.AgentConfigID,
			&i.Timestamp,
			&i.Type,
			&i.Src,
			&i.Dst,
			&i.Method,
			&i.StopReason,
			&i.HopCount,
			&i.PathHash,
			&i.Raw,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

type InsertTraceHopParams struct {
	Timestamp     pgtype.Timestamptz
	MeasurementID pgtype.UUID
	Ip            *netip.Addr
	Ttl           int32
	Rtt           pgtype.Int8
	IcmpType      pgtype.Int4
	IcmpCode      pgtype.Int4
	ReplyTtl      pgtype.Int4
	Asn           pgtype.Int4
	IsNoHop       bool
}

const insertTraceMeasurement = `-- name: InsertTraceMeasurement :one
INSERT INTO trace_measurements
(serial_id, agent_config_id, timestamp, type, src, dst, method, stop_reason, hop_count, path_hash, raw)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, serial_id, agent_config_id, timestamp, type, src, dst, method, stop_reason, hop_count, path_hash, raw
`

type InsertTraceMeasurementParams struct {
	SerialID      string
	AgentConfigID pgtype.UUID
	Timestamp     pgtype.Timestamptz
	Type          string
	Src           netip.Addr
	Dst           netip.Addr
	Method        string
	StopReason    string
	HopCount      int32
	PathHash      string
	Raw           []byte
}

func (q *Queries) InsertTraceMeasurement(ctx context.Context, arg InsertTraceMeasurementParams) (TraceMeasurement, error) {
	row := q.db.QueryRow(ctx, insertTraceMeasurement,
		arg.SerialID,
		arg.AgentConfigID,
		arg.Timestamp,
		arg.Type,
		arg.Src,
		arg.Dst,
		arg.Method,
		arg.StopReason,
		arg.HopCount,
		arg.PathHash,
		arg.Raw,
	)
	var i TraceMeasurement
	err := row.Scan(
		&i.ID,
		&i.SerialID,
		&i.AgentConfigID,
		&i.Timestamp,
		&i.Type,
		&i.Src,
		&i.Dst,
		&i.Method,
		&i.StopReason,
		&i.HopCount,
		&i.PathHash,
		&i.Raw,
	)
	return i, err
}

type UpsertAsDetailsParams struct {
	Ip        netip.Addr
	Asn       pgtype.Int4
	BgpPrefix pgtype.Text
	Name      pgtype.Text
	Cc        pgtype.Text
}
