// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package traceprocessor_db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const getHopsByMeasurement = `-- name: GetHopsByMeasurement :many
SELECT timestamp, measurement_id, ip, ttl, rtt_ms, icmp_type, icmp_code, reply_ttl, asn, is_no_hop FROM trace_hops
WHERE measurement_id = $1
ORDER BY ttl ASC
`

func (q *Queries) GetHopsByMeasurement(ctx context.Context, measurementID pgtype.UUID) ([]TraceHop, error) {
	rows, err := q.db.Query(ctx, getHopsByMeasurement, measurementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TraceHop
	for rows.Next() {
		var i TraceHop
		if err := rows.Scan(
			&i.Timestamp,
			&i.MeasurementID,
			&i.Ip,
			&i.Ttl,
			&i.RttMs,
			&i.IcmpType,
			&i.IcmpCode,
			&i.ReplyTtl,
			&i.Asn,
			&i.IsNoHop,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMeasurementsByPath = `-- name: GetMeasurementsByPath :many
SELECT id, timestamp, type, src, dst, method, stop_reason, hop_count, path_hash, raw FROM trace_measurements
WHERE src = $1
  AND dst = $2
  AND timestamp > NOW() - $3::interval
ORDER BY timestamp DESC
`

type GetMeasurementsByPathParams struct {
	Src     netip.Addr
	Dst     netip.Addr
	Column3 pgtype.Interval
}

func (q *Queries) GetMeasurementsByPath(ctx context.Context, arg GetMeasurementsByPathParams) ([]TraceMeasurement, error) {
	rows, err := q.db.Query(ctx, getMeasurementsByPath, arg.Src, arg.Dst, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TraceMeasurement
	for rows.Next() {
		var i TraceMeasurement
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.Type,
			&i.Src,
			&i.Dst,
			&i.Method,
			&i.StopReason,
			&i.HopCount,
			&i.PathHash,
			&i.Raw,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTraceHop = `-- name: InsertTraceHop :exec
INSERT INTO trace_hops
    (timestamp, measurement_id, ip, ttl, rtt_ms, icmp_type, icmp_code, reply_ttl, asn, is_no_hop)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertTraceHopParams struct {
	Timestamp     pgtype.Timestamptz
	MeasurementID pgtype.UUID
	Ip            *netip.Addr
	Ttl           int32
	RttMs         pgtype.Float8
	IcmpType      pgtype.Int4
	IcmpCode      pgtype.Int4
	ReplyTtl      pgtype.Int4
	Asn           pgtype.Int4
	IsNoHop       bool
}

func (q *Queries) InsertTraceHop(ctx context.Context, arg InsertTraceHopParams) error {
	_, err := q.db.Exec(ctx, insertTraceHop,
		arg.Timestamp,
		arg.MeasurementID,
		arg.Ip,
		arg.Ttl,
		arg.RttMs,
		arg.IcmpType,
		arg.IcmpCode,
		arg.ReplyTtl,
		arg.Asn,
		arg.IsNoHop,
	)
	return err
}

const insertTraceMeasurement = `-- name: InsertTraceMeasurement :one
INSERT INTO trace_measurements
    (timestamp, type, src, dst, method, stop_reason, hop_count, path_hash, raw)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, timestamp, type, src, dst, method, stop_reason, hop_count, path_hash, raw
`

type InsertTraceMeasurementParams struct {
	Timestamp  pgtype.Timestamptz
	Type       string
	Src        netip.Addr
	Dst        netip.Addr
	Method     string
	StopReason string
	HopCount   int32
	PathHash   string
	Raw        []byte
}

func (q *Queries) InsertTraceMeasurement(ctx context.Context, arg InsertTraceMeasurementParams) (TraceMeasurement, error) {
	row := q.db.QueryRow(ctx, insertTraceMeasurement,
		arg.Timestamp,
		arg.Type,
		arg.Src,
		arg.Dst,
		arg.Method,
		arg.StopReason,
		arg.HopCount,
		arg.PathHash,
		arg.Raw,
	)
	var i TraceMeasurement
	err := row.Scan(
		&i.ID,
		&i.Timestamp,
		&i.Type,
		&i.Src,
		&i.Dst,
		&i.Method,
		&i.StopReason,
		&i.HopCount,
		&i.PathHash,
		&i.Raw,
	)
	return i, err
}
