// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package stampprocessor_db

import (
	"context"
)

// iteratorForInsertStampProbes implements pgx.CopyFromSource.
type iteratorForInsertStampProbes struct {
	rows                 []InsertStampProbesParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertStampProbes) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertStampProbes) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].MeasurementID,
		r.rows[0].Tx,
		r.rows[0].IsLost,
		r.rows[0].Rx,
		r.rows[0].Rtt,
		r.rows[0].ForwardDelay,
		r.rows[0].BackwardDelay,
	}, nil
}

func (r iteratorForInsertStampProbes) Err() error {
	return nil
}

func (q *Queries) InsertStampProbes(ctx context.Context, arg []InsertStampProbesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"stamp_probes"}, []string{"measurement_id", "tx", "is_lost", "rx", "rtt", "forward_delay", "backward_delay"}, &iteratorForInsertStampProbes{rows: arg})
}
