// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package pingprocessor_db

import (
	"context"
)

// iteratorForInsertPingProbes implements pgx.CopyFromSource.
type iteratorForInsertPingProbes struct {
	rows                 []InsertPingProbesParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertPingProbes) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertPingProbes) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].MeasurementID,
		r.rows[0].Tx,
		r.rows[0].Rx,
		r.rows[0].IsLost,
		r.rows[0].Seq,
		r.rows[0].Rtt,
	}, nil
}

func (r iteratorForInsertPingProbes) Err() error {
	return nil
}

func (q *Queries) InsertPingProbes(ctx context.Context, arg []InsertPingProbesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"ping_probes"}, []string{"measurement_id", "tx", "rx", "is_lost", "seq", "rtt"}, &iteratorForInsertPingProbes{rows: arg})
}
