// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pingprocessor_db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PingMeasurement struct {
	ID            pgtype.UUID
	Timestamp     pgtype.Timestamptz
	SerialID      string
	AgentConfigID pgtype.UUID
	Target        string
	Sent          int32
	Received      int32
	Loss          float64
	RttMinNs      int64
	RttAvgNs      int64
	RttMaxNs      int64
	RttP50Ns      int64
	RttP95Ns      int64
	RttStddevNs   int64
}

type PingProbe struct {
	MeasurementID pgtype.UUID
	Tx            pgtype.Timestamptz
	Rx            pgtype.Timestamptz
	IsLost        bool
	Seq           pgtype.Int4
	Rtt           pgtype.Int8
}
