// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package pingprocessor_db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertPingMeasurement = `-- name: InsertPingMeasurement :one
INSERT INTO ping_measurements (timestamp, serial_id, agent_config_id, target, sent, received, loss, rtt_min_ns, rtt_avg_ns, rtt_max_ns, rtt_p50_ns, rtt_p95_ns, rtt_stddev_ns)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id
`

type InsertPingMeasurementParams struct {
	Timestamp     pgtype.Timestamptz
	SerialID      string
	AgentConfigID pgtype.UUID
	Target        string
	Sent          int32
	Received      int32
	Loss          float64
	RttMinNs      int64
	RttAvgNs      int64
	RttMaxNs      int64
	RttP50Ns      int64
	RttP95Ns      int64
	RttStddevNs   int64
}

func (q *Queries) InsertPingMeasurement(ctx context.Context, arg InsertPingMeasurementParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertPingMeasurement,
		arg.Timestamp,
		arg.SerialID,
		arg.AgentConfigID,
		arg.Target,
		arg.Sent,
		arg.Received,
		arg.Loss,
		arg.RttMinNs,
		arg.RttAvgNs,
		arg.RttMaxNs,
		arg.RttP50Ns,
		arg.RttP95Ns,
		arg.RttStddevNs,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

type InsertPingProbesParams struct {
	MeasurementID pgtype.UUID
	Tx            pgtype.Timestamptz
	Rx            pgtype.Timestamptz
	IsLost        bool
	Seq           pgtype.Int4
	Rtt           pgtype.Int8
}
